### ISSUE TITLE
8/8 Wendy  檢查 9

### ISSUE THREAD

**Issue by Ed-Law** [alanyang/public-definer#14]
![CleanShot 2024-08-08 at 11 06 31](https://github.com/user-attachments/assets/db77c616-d3b5-4055-870c-2e48bd81f670)

加client 彈走了 

![CleanShot 2024-08-08 at 15 31 09](https://github.com/user-attachments/assets/9898df6d-8181-47c4-8e14-51f56848e9d3)
改comment  最好匿名也可 comment

**Comment by wendy0911** [comment]
client 彈走 已fix

**Comment by wendy0911** [comment]
已修改但是计算总评分规则需要再确认，因为少了两个评估项
