### ISSUE TITLE
19/8 Wendy 10 

### ISSUE THREAD

**Issue by Ed-Law** [alanyang/public-definer#20]
![CleanShot 2024-08-21 at 22 56 56](https://github.com/user-attachments/assets/e5e1024c-f6c9-416c-bfa8-465f2d98851f)
頁數沒變 
hover 有顏色 

能不上傳時測像素，不夠的會提醒不清

![CleanShot 2024-08-19 at 13 34 41](https://github.com/user-attachments/assets/d26d58f3-e73c-4820-842f-be7cf0297ead)
上傳檔案自動改名稱  V1, V2, V3 如此類推 

![image](https://github.com/user-attachments/assets/5b7b3f9e-242c-4d0c-9f15-8f6892ccb4e5)

檔案名稱 ＝ INV-數字 + 機構名稱 
裏面檔案 INV-數字 + 機構名稱 + V1....

**Comment by wendy0911** [comment]
除档案名称修改部分，都已修改完毕
