### ISSUE TITLE
Wendy 26/8 

### ISSUE THREAD

**Issue by Ed-Law** [alanyang/public-definer#26]
![CleanShot 2024-09-13 at 11 18 39@2x](https://github.com/user-attachments/assets/52213e1f-f7ae-4ff1-90b3-ac174109988d)
https://go.definertech.com/share/document/9892245f2882a93b7913319a5f1e0c69540c570e7eb1b1168d5eede6c41162cf9004e11b829442fb7217bf286b0fc2d445527f70f44101b9236ddc0b536f8983f97f2e0dfdca69b9a837787851464341
左右不就滾盡 

![CleanShot 2024-09-11 at 22 48 11](https://github.com/user-attachments/assets/d42503e0-1436-4ce6-8947-4ae794f96f84)
手機版; 突然 選了兩個tab 

![CleanShot 2024-09-11 at 23 08 08](https://github.com/user-attachments/assets/9aae61bf-c11d-4e55-8330-64e23a0e7aa8)
展示內容，可改description 

![image](https://github.com/user-attachments/assets/caf48f23-8121-4538-98dd-2d1db88e9a3d)

上傳右下角 loading 用Yang 的組件

![CleanShot 2024-09-06 at 23 01 58](https://github.com/user-attachments/assets/cf85b170-4978-4fee-917d-6fcac27c4864)

![CleanShot 2024-08-30 at 20 47 44](https://github.com/user-attachments/assets/8dfe0e79-f692-4bb6-addd-092581014157)
左上角 可返回 

![CleanShot 2024-08-28 at 02 28 58](https://github.com/user-attachments/assets/f2f163c9-3799-4eaf-9efc-6be0ddc5e329)
點圖預示，點圖標下載 

![CleanShot 2024-08-26 at 23 15 46](https://github.com/user-attachments/assets/a653173f-ef2b-4ee8-9824-0be2734d9def)
顯客戶名稱 

![CleanShot 2024-08-26 at 10 09 27](https://github.com/user-attachments/assets/4f70d964-31b3-47ae-b16b-0c773d4c0fd9)
改了內容 invoke code 應該沒改 可檢查一下 ～

![image](https://github.com/user-attachments/assets/cd5c2964-8204-4b11-bcac-d7440d788802)
加了這4個新的 原本沒有～

ipad 标注功能 画笔功能可用ipad 画

![CleanShot 2024-08-26 at 10 51 08](https://github.com/user-attachments/assets/88021a9d-c2ec-4b48-8abe-cebdc646fc1b)
付款前可輸電郵、下載單據？

**Comment by wendy0911** [comment]
除上传设计稿loading无法在右下角外，以及project 里有undefind内容外都已修改完毕
