### ISSUE TITLE
26/7 ENG Word/Content Issues

### ISSUE THREAD

**Issue by Dani-hkdp** [alanyang/public-definer#3]
<img width="1387" alt="Screenshot 2024-07-26 at 7 01 33 AM" src="https://github.com/user-attachments/assets/c46329cb-10aa-44b4-b745-39add6b67f10">

Change to 'Review Designs'

**Comment by Dani-hkdp** [comment]
<img width="1381" alt="Screenshot 2024-07-26 at 7 35 20 AM" src="https://github.com/user-attachments/assets/f0144f14-f184-4df0-99c7-2f06dddef4a2">

Headline: Ready to Level Up Your Design Career?
Body: Demonstrate your design expertise in just 15 minutes. As a platform designer, enjoy a steady stream of high-profile projects, curated client matches, and gain maximum exposure for your best work.

**Comment by Dani-hkdp** [comment]
<img width="892" alt="Screenshot 2024-07-26 at 7 45 03 AM" src="https://github.com/user-attachments/assets/2a6f0fd4-1301-41a0-ac1d-2aeb738a009a">

Exclusive for Platform Designers 
Subheadline: Unlock Exclusive Job Opportunities
Body: Ready to take on exciting design projects? Prove your skills with our quick qualification test and unlock a world of exciting projects matched to your expertise.

Button: Start Test Now

**Comment by Dani-hkdp** [comment]
<img width="719" alt="Screenshot 2024-07-26 at 8 05 24 AM" src="https://github.com/user-attachments/assets/aff90abd-6951-4686-858b-3811496342ae">


Welcome to DeFiner: Your Path to Design Success. Transform your creativity into rewarding opportunities. Discover exciting projects, connect with clients, and grow your design career.

**Comment by Dani-hkdp** [comment]
<img width="904" alt="Screenshot 2024-07-26 at 8 09 46 AM" src="https://github.com/user-attachments/assets/3bf8631e-6e59-4fed-bc9c-1d156fbd16d3">

Button: Start a New Project
Button: Build Your Portfolio

**Comment by Dani-hkdp** [comment]
<img width="1347" alt="Screenshot 2024-07-26 at 8 25 21 AM" src="https://github.com/user-attachments/assets/b213fed4-30b1-473d-8eae-8a02ee01264c">

Compensation change to 'Payments'
Design fee change to ' Design Fee

**Comment by Dani-hkdp** [comment]
<img width="829" alt="Screenshot 2024-07-26 at 8 38 28 AM" src="https://github.com/user-attachments/assets/0b542220-cae4-4610-9f65-e725dec403ef">

Priority change to 'Feature Design'

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/cb70f18a-4369-4690-9302-40674bbc71a1)

1. Updates for your order
2. All info about your order
3. Files - All files uploaded by your designer
4. Review - Rate your designer
5. Deadline
6. Your order has been place
7. Order placed
8. Please (capitalise "P")


![image](https://github.com/user-attachments/assets/d224f0f8-fcc5-4a86-952a-5a1908e2faf9)
1. Your order is now in progress.
2. We notified your designer about your project. You should receive your order by: ____



![image](https://github.com/user-attachments/assets/932aab4c-324d-4e17-9fd0-4263d761f4e3)
1. ALL "Disbursement" change to Payment
2. ALL "Remarks"  change to Comments



![image](https://github.com/user-attachments/assets/13ed6044-e66e-4e05-ba3c-4b0bb69374ab)
Comments



![image](https://github.com/user-attachments/assets/7ce4c4e0-5de3-4539-9ab5-f8a564eb54ca)
1. Applied
2. Mark All Read


![image](https://github.com/user-attachments/assets/d48d126e-91f5-4d8e-a2df-c93c5783646c)
1. Fill in your requirements to easily start your design.
2. Our intelligent system will match you with the best designers.



![image](https://github.com/user-attachments/assets/32110ef8-2b53-47e5-a465-932914a24a83)
1. What design do you need?
2. we can remove this


![image](https://github.com/user-attachments/assets/9fce180d-f732-40e1-ab10-7fd176191181)
1. Enter Project Name
2. Select...
3. Creative
4. Artistic
5. Choose your font and design style
6. Project Details - Describe your requirements for your project

![image](https://github.com/user-attachments/assets/f1b37704-bf80-494a-963a-c4d2a5c3a811)
1. Preferred Designers
2. Guided tour (Soon) //Please anything that is not a feature yet, but already has a design, put "Soon"
3. Check out top rated talents for your team (proper capitalisation)


![image](https://github.com/user-attachments/assets/fb08bf95-4a31-4fec-bf71-7065ff4536dc)
1. Designers
2.  Preferred Designers


![image](https://github.com/user-attachments/assets/b3d9a405-f017-4678-9fe3-b985e8f7b0b2)
1. Build Your Online Creative Team - Choose your design team & Manage design projects all-in-one!
2. Design Services We Offer


![image](https://github.com/user-attachments/assets/6367993c-6271-4960-94b4-2b7a48fbd174)
Our Excellent Designers


![image](https://github.com/user-attachments/assets/3e242932-3b66-490a-a0dc-c2d081e263e0)
1. Deadline
2. Comments


![image](https://github.com/user-attachments/assets/44e8ac4f-4362-41ae-bace-f7055db728df)
Dedicated Project Manager
(please check for all designs)

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/7afff8ef-0f45-48e7-9275-82e6e72c473e)
1. Your order is now in progress.
2. We notified your designer about your project. You should receive your order by: ____

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/6aa78bed-e60d-4f36-9253-77dd09dd9257)
1. Can still compress this whole section vertically
2. We can put the Client and Designer files together in section 3, then can just separate it properly in two columns. We can re-translate section 3 to Files - All Files uploaded by You and Your Designer.
3. We can put these together with in the left sidebar so we don't have clutter on top.
4. Sectioning and separation is quite confusing for all parts inside here.

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/3b1c75b2-521f-4f46-bf30-a2f5c588669a)
Whichever the title here, should strictly be the title in the box.

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/817a605a-303e-4bad-9613-e0e4125d8eba)
Utilise columns so it's easier to see all the requirements

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/75eccf06-4867-4a41-b755-e5dd1801ba16)
Separate the main sections clearly

**Comment by AndreaHKDP** [comment]
![image](https://github.com/user-attachments/assets/25d6bbb0-c008-449f-803d-d87f745c6eeb)
Utilise columns as well.
As suggested above, we can put all uploads together in this section. Just separate clearly which one is which.
Designer Folder |  Source File  |  Client Uploads 

Can also add comments per file upload, i.e. client want to briefly explain what the link/file they uploaded is about.

**Comment by wendy0911** [comment]
已修改
